name: CI

on:
  push:
    paths-ignore:
      - "**.md"

  pull_request:

  workflow_dispatch:

# Allow to stop obsolete workflows
concurrency:
  group: ci-buildtrain-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  erc-drc-checks:
    runs-on: ubuntu-latest
    if: github.ref_type != 'tag'

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: INTI-CMNB/KiBot@v2_k8
        with:
          config: Hardware/OpenMowerMainboard/OpenMowerMainboard.kibot.yaml
          board: Hardware/OpenMowerMainboard/OpenMowerMainboard.kicad_pcb
          verbose: 1
